### PR TITLE
Improved the UI

### PR DESCRIPTION
**Pull request by Edu58**
I improved the UI a bit using bootstrap. Also, refractored some useEffect hooks use cases and replaced Navigation with Link which seemed more efficient.

### CODE REVIEW

**Comment by Engineervinay** [comment]
Hey @Edu58  thank you for contributing, can you share some screenshots of how the website looks after making changes?

**Comment by Edu58** [comment]
## New homepage UI
homepage

## New details page UI
details

**Comment by Edu58** [comment]
> Hey @Edu58 thank you for contributing, can you share some screenshots of how the website looks after making changes?

I just shared the screenshots of the new UI

**Comment by Engineervinay** [comment]
@Edu58  Merged 👍

**Pull request merged**
